### ISSUE TITLE
cffi dependency not automatically installed when installing cairocffi in Windows

### ISSUE THREAD

**Issue by OskarPersson** [Kozea/cairocffi#115]
Not really sure if this is an issue for cairocffi, cffi, pip or something else but when I try to install cairocffi on a new Windows machine running Python 2.7.15 I get an error if I don't first run `pip install cffi` before `pip install cairocffi`:

```
PS C:\Windows\system32> pip install cairocffi
Collecting cairocffi
  Downloading https://files.pythonhosted.org/packages/62/be/ad4d422b6f38d99b09ad6d046ab725e8ccac5fefd9ca256ca35a80dbf3c6
/cairocffi-0.9.0.tar.gz (84kB)
    100% |################################| 92kB 2.0MB/s
    Complete output from command python setup.py egg_info:
    c:\python27\lib\site-packages\setuptools\pep425tags.py:89: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Pyth
on ABI tag may be incorrect
      warn=(impl == 'cp')):
    c:\python27\lib\site-packages\setuptools\pep425tags.py:93: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset,
 Python ABI tag may be incorrect
      warn=(impl == 'cp')):
    c:\python27\lib\site-packages\setuptools\pep425tags.py:99: RuntimeWarning: Config variable 'Py_UNICODE_SIZE' is unse
t, Python ABI tag may be incorrect
      sys.version_info < (3, 3))) \
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\vagrant\appdata\local\temp\pip-build-pksjnk\cairocffi\setup.py", line 51, in <module>
        'test': ['pytest-runner', 'pytest-cov'],
      File "c:\python27\lib\site-packages\setuptools\__init__.py", line 128, in setup
        _install_setup_requires(attrs)
      File "c:\python27\lib\site-packages\setuptools\__init__.py", line 123, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 513, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 774, in resolve
        replace_conflicting=replace_conflicting
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1057, in best_match
        return self.obtain(req, installer)
      File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 1069, in obtain
        return installer(requirement)
      File "c:\python27\lib\site-packages\setuptools\dist.py", line 580, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\python27\lib\site-packages\setuptools\command\easy_install.py", line 661, in easy_install
        not self.always_copy, self.local_index
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 653, in fetch_distribution
        dist = find(requirement)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 633, in find
        loc = self.download(dist.location, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 577, in download
        found = self._download_url(scheme.group(1), spec, tmpdir)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 822, in _download_url
        return self._attempt_download(url, filename)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 828, in _attempt_download
        headers = self._download_to(url, filename)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 727, in _download_to
        fp = self.open_url(url)
      File "c:\python27\lib\site-packages\setuptools\package_index.py", line 778, in open_url
        % (url, v.reason))
    distutils.errors.DistutilsError: Download error for https://files.pythonhosted.org/packages/89/12/684bad296567b9300c
7ac82a4f635b489ed589fa7c0bb2042208e3c020e3/cffi-1.11.5-cp27-cp27m-win_amd64.whl#sha256=79f9b6f7c46ae1f8ded75f68cf8ad50e5
729ed4d590c74840471fc2823457d04: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
```

**Comment by OskarPersson** [comment]
@liZe Are you sure? Like I said, downloading cffi first (`pip install cffi`) and then downloading cairocffi works without any problems.

**Comment by liZe** [comment]
> Are you sure?

I'm not, but the error message is pretty explicit. Maybe using `pip install cffi` directly doesn't follow the same code path as installing cffi as a cairocffi dependency. There's also maybe something wrong with your Python install, the `RuntimeWarning`s are a bit strange.

**Comment by liZe** [comment]
@OskarPersson Is there anything else I can do to help you?

**Comment by OskarPersson** [comment]
Sorry for a late answer but this was (like you suspected) something wrong with the Python installation that was done using "choco install python". Installing Python from the official website solved it.

**Comment by liZe** [comment]
> Installing Python from the official website solved it.

Good to know, thank you!
