### ISSUE TITLE
Mysterious pip install failure with updated packages: ModuleNotFoundError

### ISSUE THREAD

**Issue by E3V3A** [Kozea/cairocffi#117]
I get a very strange error when trying to install. The error is: 

**`ModuleNotFoundError: No module named 'cffi.setuptools_ext'`**

This is what I do:
```bash 
# pip3 install --no-cache-dir cairocffi

Collecting cairocffi
  Downloading https://files.pythonhosted.org/packages/62/be/ad4d422b6f38d99b09ad6d046ab725e8ccac5fefd9ca256ca35a80dbf3c6/cairocffi-0.9.0.tar.gz (84kB)
    100% |████████████████████████████████| 92kB 1.4MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jq4orjvu/cairocffi/setup.py", line 51, in <module>
        'test': ['pytest-runner', 'pytest-cov'],
      File "/usr/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.6/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.6/distutils/dist.py", line 281, in __init__
        self.finalize_options()
      File "/usr/lib/python3.6/site-packages/setuptools/dist.py", line 529, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
        return self.resolve()
      File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
    ModuleNotFoundError: No module named 'cffi.setuptools_ext'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-jq4orjvu/cairocffi/
```

I'm quite confident I'm using the latest of everything, but it seem that something is missing or perhaps interfering. Please see links below for more details of my installation. 

---

This problem is also tracked here:
https://github.com/pygobject/pycairo/issues/135
and here:
https://github.com/pyca/bcrypt/issues/157

**Comment by E3V3A** [comment]
Yep, something definitely not right:

```python
>>> import cffi
>>> cffi.__file__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'cffi' has no attribute '__file__'
```

I'm re-installing all the stuff and see if this resolves it.

**Comment by lukashawer** [comment]
when I try to install cairocffi i got:

C:\WINDOWS\system32>pip3 install --no-cache-dir cairocffi
Collecting cairocffi
  Downloading https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031a/cairocffi-1.1.0.tar.gz (68kB)
     |████████████████████████████████| 71kB 1.1MB/s
    ERROR: Command errored out with exit status 1:
     command: 'c:\programdata\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LUH\\AppData\\Local\\Temp\\pip-install-wxdds8wd\\cairocffi\\setup.py'"'"'; __file__='"'"'C:\\Users\\LUH\\AppData\\Local\\Temp\\pip-install-wxdds8wd\\cairocffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\LUH\AppData\Local\Temp\pip-install-wxdds8wd\cairocffi\pip-egg-info'
         cwd: C:\Users\LUH\AppData\Local\Temp\pip-install-wxdds8wd\cairocffi\
    Complete output (25 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\LUH\AppData\Local\Temp\pip-install-wxdds8wd\cairocffi\setup.py", line 13, in <module>
        'cairocffi/ffi_build.py:ffi_pixbuf']
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\programdata\anaconda3\lib\distutils\core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\dist.py", line 448, in __init__
        k: v for k, v in attrs.items()
      File "c:\programdata\anaconda3\lib\distutils\dist.py", line 292, in __init__
        self.finalize_options()
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\dist.py", line 740, in finalize_options
        ep.load()(self)
      File "c:\programdata\anaconda3\lib\site-packages\setuptools\dist.py", line 747, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "C:\Users\LUH\AppData\Roaming\Python\Python37\site-packages\cffi\setuptools_ext.py", line 217, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "C:\Users\LUH\AppData\Roaming\Python\Python37\site-packages\cffi\setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "C:\Users\LUH\AppData\Roaming\Python\Python37\site-packages\cffi\setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "cairocffi/ffi_build.py", line 28, in <module>
        ffi.cdef(constants._CAIRO_HEADERS)
    AttributeError: module 'constants' has no attribute '_CAIRO_HEADERS'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Please advice

**Comment by dvaraujo** [comment]
> Today I updated everything and managed to re-install cffi properly with:
> 
> ```shell
> pip3 install --no-cache-dir --force-reinstall cffi
> pip3 install --no-cache-dir cairocffi
> ```
> 
> 🌞

Saved my life, thank you very much.
