### ISSUE TITLE
cairo 1.0.22 install broken with pip on Python 2.7

### ISSUE THREAD

**Issue by tirkarthi** [Kozea/cairocffi#122]
We are using `CairoSVG==1.0.22` in our requirements with Python 2.7 and suddenly it causes failure on installing from pip. It seems that there is an error introduced with 860538e1eb1098cb04c2f175c1fd3e673216ffe8 and this was also seems to be pushed to PyPI as 1.0.0 thus causing the failure. It would be helpful to know if the change to older version to introduce this error is intentional and if so how we can proceed with installing a compatible version.

Installation traceback : 

```
pip install --ignore-installed CairoSVG==1.0.22
Collecting CairoSVG==1.0.22
Collecting cairocffi (from CairoSVG==1.0.22)
  Using cached https://files.pythonhosted.org/packages/33/33/a6aac7bace71019712fbc34f4ceb9d90c23f8fbadf2ac48f771aef9c1431/cairocffi-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2b/mhgtnnpx4z943t4cc9yvw4qw0000gn/T/pip-build-kINqDH/cairocffi/setup.py", line 7, in <module>
        'cairocffi does not support Python 2.x anymore. '
    RuntimeError: cairocffi does not support Python 2.x anymore. Please use Python 3 or install an older version of cairocffi.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2b/mhgtnnpx4z943t4cc9yvw4qw0000gn/T/pip-build-kINqDH/cairocffi/
```

File from PyPI : 

```
(virtual-next) ➜  wget https://files.pythonhosted.org/packages/33/33/a6aac7bace71019712fbc34f4ceb9d90c23f8fbadf2ac48f771aef9c1431/cairocffi-1.0.0.tar.gz
--2019-02-11 18:28:48--  https://files.pythonhosted.org/packages/33/33/a6aac7bace71019712fbc34f4ceb9d90c23f8fbadf2ac48f771aef9c1431/cairocffi-1.0.0.tar.gz
Resolving files.pythonhosted.org... 151.101.129.63, 151.101.1.63, 151.101.193.63, ...
Connecting to files.pythonhosted.org|151.101.129.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 68570 (67K) [binary/octet-stream]
Saving to: ‘cairocffi-1.0.0.tar.gz’

cairocffi-1.0.0.tar.gz      100%[=========================================>]  66.96K   242KB/s    in 0.3s

2019-02-11 18:28:49 (242 KB/s) - ‘cairocffi-1.0.0.tar.gz’ saved [68570/68570]

(virtual-next) ➜  tar xvf cairocffi-1.0.0.tar.gz
x cairocffi-1.0.0/
x cairocffi-1.0.0/LICENSE
x cairocffi-1.0.0/PKG-INFO
x cairocffi-1.0.0/README.rst
x cairocffi-1.0.0/cairocffi/
x cairocffi-1.0.0/cairocffi/VERSION
x cairocffi-1.0.0/cairocffi/__init__.py
x cairocffi-1.0.0/cairocffi/constants.py
x cairocffi-1.0.0/cairocffi/context.py
x cairocffi-1.0.0/cairocffi/ffi_build.py
x cairocffi-1.0.0/cairocffi/fonts.py
x cairocffi-1.0.0/cairocffi/matrix.py
x cairocffi-1.0.0/cairocffi/patterns.py
x cairocffi-1.0.0/cairocffi/pixbuf.py
x cairocffi-1.0.0/cairocffi/surfaces.py
x cairocffi-1.0.0/cairocffi/test_cairo.py
x cairocffi-1.0.0/cairocffi/test_pixbuf.py
x cairocffi-1.0.0/cairocffi/test_xcb.py
x cairocffi-1.0.0/cairocffi/xcb.py
x cairocffi-1.0.0/cairocffi.egg-info/
x cairocffi-1.0.0/cairocffi.egg-info/PKG-INFO
x cairocffi-1.0.0/cairocffi.egg-info/SOURCES.txt
x cairocffi-1.0.0/cairocffi.egg-info/dependency_links.txt
x cairocffi-1.0.0/cairocffi.egg-info/requires.txt
x cairocffi-1.0.0/cairocffi.egg-info/top_level.txt
x cairocffi-1.0.0/setup.cfg
x cairocffi-1.0.0/setup.py
(virtual-next) ➜  cd cairocffi-1.0.0
(virtual-next) ➜  cairocffi-1.0.0 grep -i 'support ' setup.py
        'cairocffi does not support Python 2.x anymore. '
```

Thanks

**Comment by tirkarthi** [comment]
It seems the version of cairocffi is not pinned in `install_requires` in setup.py for cairosvg causing this error by picking up the latest version released during installation.

**Comment by liZe** [comment]
> It seems the version of cairocffi is not pinned in `install_requires` in setup.py for cairosvg causing this error by picking up the latest version released during installation.

True. I transfer the issue on CairoSVG.
