### ISSUE TITLE
Installing on Windows - 32bit Python 3.8.0

### ISSUE THREAD

**Issue by daniel-butler** [Kozea/cairocffi#142]
Following these instructions I've installed the GTK library https://weasyprint.readthedocs.io/en/stable/install.html#windows I think I saved the kittens, but afraid that I haven't!

When installing cairocffi this is the error that is produced:
```(venv3-8-0) PS C:\ProgramData\CoreCustom\electronic-payments> python -m pip install cairocffi
Collecting cairocffi
  Using cached https://files.pythonhosted.org/packages/f7/99/b3a2c6393563ccbe081ffcceb359ec27a6227792c5169604c1bd8128031
a/cairocffi-1.1.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\Scripts\python.exe' -c 'import sys, setuptools, t
okenize; sys.argv[0] = '"'"'C:\\Users\\AccountingService\\AppData\\Local\\Temp\\pip-install-8zek1uug\\cairocffi\\setup.p
y'"'"'; __file__='"'"'C:\\Users\\AccountingService\\AppData\\Local\\Temp\\pip-install-8zek1uug\\cairocffi\\setup.py'"'"'
;f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(
compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\AccountingService\AppData\Local\Temp\pip-install
-8zek1uug\cairocffi\pip-egg-info'
         cwd: C:\Users\AccountingService\AppData\Local\Temp\pip-install-8zek1uug\cairocffi\
    Complete output (106 lines):
    Traceback (most recent call last):
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 154,
in save_modules
        yield saved
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 195,
in setup_context
        yield
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 250,
in run_setup
        _execfile(setup_script, ns)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 45, i
n _execfile
        exec(code, globals, locals)
      File "C:\Users\ACCOUN~1\AppData\Local\Temp\easy_install-jj1h8lup\cffi-1.13.2\setup.py", line 127, in <module>
      File "C:\Users\ACCOUN~1\AppData\Local\Temp\easy_install-jj1h8lup\cffi-1.13.2\setup.py", line 105, in uses_msvc
      File "c:\users\accountingservice\appdata\local\programs\python\python38-32\Lib\distutils\command\config.py", line
225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\users\accountingservice\appdata\local\programs\python\python38-32\Lib\distutils\command\config.py", line
127, in _compile
        src = self._gen_temp_sourcefile(body, headers, lang)
      File "c:\users\accountingservice\appdata\local\programs\python\python38-32\Lib\distutils\command\config.py", line
109, in _gen_temp_sourcefile
        with open(filename, "w") as file:
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 418,
in _open
        self._violation("open", path, mode, *args, **kw)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 407,
in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: open('_configtest.c', 'w') {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\AccountingService\AppData\Local\Temp\pip-install-8zek1uug\cairocffi\setup.py", line 10, in <module>

        setup(
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\__init__.py", line 144,
 in setup
        _install_setup_requires(attrs)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\__init__.py", line 139,
 in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\dist.py", line 717, in
fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\pkg_resources\__init__.py", line 7
80, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\pkg_resources\__init__.py", line 1
065, in best_match
        return self.obtain(req, installer)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\pkg_resources\__init__.py", line 1
077, in obtain
        return installer(requirement)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\dist.py", line 787, in
fetch_build_egg
        return cmd.easy_install(req)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\command\easy_install.py
", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\command\easy_install.py
", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\command\easy_install.py
", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\command\easy_install.py
", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\command\easy_install.py
", line 1144, in run_setup
        run_setup(setup_script, args)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 253,
in run_setup
        raise
      File "c:\users\accountingservice\appdata\local\programs\python\python38-32\Lib\contextlib.py", line 131, in __exit
__
        self.gen.throw(type, value, traceback)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 195,
in setup_context
        yield
      File "c:\users\accountingservice\appdata\local\programs\python\python38-32\Lib\contextlib.py", line 131, in __exit
__
        self.gen.throw(type, value, traceback)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 166,
in save_modules
        saved_exc.resume()
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 141,
in resume
        six.reraise(type, exc, self._tb)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\_vendor\six.py", line 6
85, in reraise
        raise value.with_traceback(tb)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 154,
in save_modules
        yield saved
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 195,
in setup_context
        yield
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 250,
in run_setup
        _execfile(setup_script, ns)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 45, i
n _execfile
        exec(code, globals, locals)
      File "C:\Users\ACCOUN~1\AppData\Local\Temp\easy_install-jj1h8lup\cffi-1.13.2\setup.py", line 127, in <module>
      File "C:\Users\ACCOUN~1\AppData\Local\Temp\easy_install-jj1h8lup\cffi-1.13.2\setup.py", line 105, in uses_msvc
      File "c:\users\accountingservice\appdata\local\programs\python\python38-32\Lib\distutils\command\config.py", line
225, in try_compile
        self._compile(body, headers, include_dirs, lang)
      File "c:\users\accountingservice\appdata\local\programs\python\python38-32\Lib\distutils\command\config.py", line
127, in _compile
        src = self._gen_temp_sourcefile(body, headers, lang)
      File "c:\users\accountingservice\appdata\local\programs\python\python38-32\Lib\distutils\command\config.py", line
109, in _gen_temp_sourcefile
        with open(filename, "w") as file:
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 418,
in _open
        self._violation("open", path, mode, *args, **kw)
      File "C:\ProgramData\CoreCustom\electronic-payments\venv3-8-0\lib\site-packages\setuptools\sandbox.py", line 407,
in _violation
        raise SandboxViolation(operation, args, kw)
    setuptools.sandbox.SandboxViolation: SandboxViolation: open('_configtest.c', 'w') {}

    The package setup script has attempted to modify files on your system
    that are not within the EasyInstall build area, and has been aborted.

    This package cannot be safely installed by EasyInstall, and may not
    support alternate installation locations even if you run its setup
    script by hand.  Please inform the package's author and the EasyInstall
    maintainers to find out if a fix or workaround is available.

    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by daniel-butler** [comment]
The issue was I didn't set my path to the msys library correctly

**Comment by julianstirling** [comment]
@daniel-butler Do you have more details on this fix. I am getting the exact same error on a Windows CI, and it is taking me about 40 mins to try each new command as I don't have a windows machine.
