### ISSUE TITLE
python 2.7 issue?

### ISSUE THREAD

**Issue by aster94** [Kozea/cairocffi#145]
Hello

I tried to install cairocffi with the above setup
```
PS C:\Users\vincenzo> pip-kicad --version
pip 19.2.3 from C:\Program Files\KiCad\lib\python2.7\site-packages\pip (python 2.7)

PS C:\Users\vincenzo> python-kicad
Python 2.7.16 (default, Aug 15 2019, 17:51:40) [GCC 9.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> ^Z
```

tried from pip
```
 pip-kicad install cairocffi
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting cairocffi
  Using cached https://files.pythonhosted.org/packages/62/be/ad4d422b6f38d99b09ad6d046ab725e8ccac5fefd9ca256ca35a80dbf3c6/cairocffi-0.9.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:/Program Files/KiCad/bin/python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\vincenzo\\appdata\\local\\temp\\pip-install-y3nwwt\\cairocffi\\setup.py'"'"'; __file__='"'"'c:\\users\\vincenzo\\appdata\\local\\temp\\pip-install-y3nwwt\\cairocffi\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: c:\users\vincenzo\appdata\local\temp\pip-install-y3nwwt\cairocffi\
    Complete output (42 lines):

        No working compiler found, or bogus compiler options passed to
        the compiler from Python's standard "distutils" module.  See
        the error messages above.  Likely, the problem is not related
        to CFFI but generic to the setup.py of any Python package that
        tries to compile C code.  (Hints: on OS/X 10.8, for errors about
        -mno-fused-madd see http://stackoverflow.com/questions/22313407/
        Otherwise, see https://wiki.python.org/moin/CompLangPython or
        the IRC channel #python on irc.freenode.net.)

        Trying to continue anyway.  If you are trying to install CFFI from
        a build done in a different context, you can ignore this warning.

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\vincenzo\appdata\local\temp\pip-install-y3nwwt\cairocffi\setup.py", line 51, in <module>
        'test': ['pytest-runner', 'pytest-cov'],
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/dist.py", line 719, in fetch_build_eggs
        replace_conflicting=True,
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/pkg_resources/__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/pkg_resources/__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/pkg_resources/__init__.py", line 1077, in obtain
        return installer(requirement)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\Program Files\KiCad\lib\python2.7\site-packages/setuptools/command/easy_install.py", line 1146, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-w64-mingw32-gcc' failed: No such file or directory
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

okkk looks like i don't have a compiler, i don't wish to install any, so let's go to https://www.lfd.uci.edu/~gohlke/pythonlibs/ and install the wheel package directly:

```
PS C:\Users\vincenzo> pip-kicad install $env:desktop/cairocffi-0.9.0-cp27-cp27m-win32.whl
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/developmen...-2-support
ERROR: cairocffi-0.9.0-cp27-cp27m-win32.whl is not a supported wheel on this platform.

PS C:\Users\vincenzo> pip-kicad install $env:desktop/cairocffi-0.9.0-cp27-cp27m-win_amd64.whl
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/developmen...-2-support
ERROR: cairocffi-0.9.0-cp27-cp27m-win_amd64.whl is not a supported wheel on this platform.
```

How could it be possible that any of the two is installable on my machine?

I didn't faced any problem installing cairo/cairocffi on the same computer with python 3.7

**Comment by cgohlke** [comment]
> How could it be possible that any of the two is installable on my machine?

That's because KiCad's Python 2.7 is a mingw build, which is not compatible with the official Visual Studio 2008 build from python.org.

**Comment by aster94** [comment]
Hello Gohlke, thanks for your wheels package!
sorry but I would like to understand this better and my knowledge are not that good:
So python can be build both with mingw and VS (or I guess any other C compiler), the kicad team decided to built it with mingw. Why if I try to install a package build with another compiler it won't work? And if I understood it correctly how could I achieve this without installing the whole mingw?

**Comment by liZe** [comment]
Now that Python 2 is not supported anymore and that CairoCFFI will drop Python 2 support, I think that I can safely close this issue…
