### ISSUE TITLE
error happened when I import cairocffi

### ISSUE THREAD

**Issue by busyyang** [Kozea/cairocffi#154]
I run python3.7 on win10 machine. An error happened, when run code of `import cairocffi`. And I make sure I installed gtk and added in `PATH`.

Traceback (most recent call last):
  File "E:/03personal/DeepLearning/keras_series_code/04Keras进行OCR/keras_ocr.py", line 7, in <module>
    import cairocffi as cairo
  File "D:\ProgramData\Anaconda3\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "D:\ProgramData\Anaconda3\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0xc1

**Comment by liZe** [comment]
Error 0xc1 seems to mean that cairocffi finds the library but cannot load it. Did you mix 32 and 64 bit libraries (for example Python 32 bit and GTK 64 bit)?

**Comment by busyyang** [comment]
Thanks for the feedback. I did mix 32 and 64 bit libraries. I installed 32 bit GTK libs on 32 bit machine.
