### ISSUE TITLE
no library called "cairo" was found - version 1.1.0

### ISSUE THREAD

**Issue by milkywade** [Kozea/cairocffi#159]
Dear - I was running the code on [this page](https://pbpython.com/pdf-reports.html) [pbpython.com] and got the following exception when invoking "from weasyprint import HTML" for the first time:

```
Traceback (most recent call last):
  File "jinja_test.py", line 2, in <module>
    from weasyprint import HTML
  File "Z:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\weasyprint\__init__.py", line 440, in <module>
    from .css import preprocess_stylesheet  # noqa isort:skip
  File "Z:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\weasyprint\css\__init__.py", line 30, in <module>
    from . import computed_values, media_queries
  File "Z:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\weasyprint\css\computed_values.py", line 18, in <module>
    from .. import text
  File "Z:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\weasyprint\text.py", line 14, in <module>
    import cairocffi as cairo
  File "Z:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\cairocffi\__init__.py", line 50, in <module>
    ('libcairo.so', 'libcairo.2.dylib', 'libcairo-2.dll'))
  File "Z:\DEV\BIN\Miniconda3\envs\stocks_py35\lib\site-packages\cairocffi\__init__.py", line 45, in dlopen
    raise OSError(error_message)  # pragma: no cover
OSError: no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so': error 0x7e
cannot load library 'libcairo.2.dylib': error 0x7e
cannot load library 'libcairo-2.dll': error 0x7e
```
Here are the logs from pip:

```
Z:\DEV\>pip install weasyprint
Collecting weasyprint
  Downloading WeasyPrint-51-py3-none-any.whl (359 kB)
     |████████████████████████████████| 359 kB 2.2 MB/s
Collecting tinycss2>=1.0.0
  Downloading tinycss2-1.0.2-py3-none-any.whl (61 kB)
     |████████████████████████████████| 61 kB 29 kB/s
Requirement already satisfied: html5lib>=0.999999999 in z:\dev\bin\miniconda3\envs\stocks_py35\lib\site-packages (from weasyprint) (1.0.1)
Requirement already satisfied: setuptools>=39.2.0 in z:\dev\bin\miniconda3\envs\stocks_py35\lib\site-packages (from weasyprint) (46.4.0.post20200518)
Collecting CairoSVG>=2.4.0
  Downloading CairoSVG-2.4.2-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 1.1 MB/s
Collecting cairocffi>=0.9.0
  Downloading cairocffi-1.1.0.tar.gz (68 kB)
     |████████████████████████████████| 68 kB 890 kB/s
Collecting cssselect2>=0.1
  Downloading cssselect2-0.3.0-py3-none-any.whl (31 kB)
Collecting Pyphen>=0.9.1
  Downloading Pyphen-0.9.5-py2.py3-none-any.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 906 kB/s
Collecting cffi>=0.6
  Using cached cffi-1.14.0-cp37-cp37m-win_amd64.whl (176 kB)
Requirement already satisfied: webencodings>=0.4 in z:\dev\bin\miniconda3\envs\stocks_py35\lib\site-packages (from tinycss2>=1.0.0->weasyprint) (0.5.1)
Requirement already satisfied: six>=1.9 in z:\dev\bin\miniconda3\envs\stocks_py35\lib\site-packages (from html5lib>=0.999999999->weasyprint) (1.14.0)
Requirement already satisfied: defusedxml in z:\dev\bin\miniconda3\envs\stocks_py35\lib\site-packages (from CairoSVG>=2.4.0->weasyprint) (0.6.0)
Collecting pillow
  Downloading Pillow-7.1.2-cp37-cp37m-win_amd64.whl (2.0 MB)
     |████████████████████████████████| 2.0 MB 3.3 MB/s
Collecting pycparser
  Using cached pycparser-2.20-py2.py3-none-any.whl (112 kB)
Building wheels for collected packages: cairocffi
  Building wheel for cairocffi (setup.py) ... done
  Created wheel for cairocffi: filename=cairocffi-1.1.0-py3-none-any.whl size=88609 sha256=f7701fb62016a620fc6f3654e22ff7ab03def52b287228e616120d4c5b2afd55
  Stored in directory: c:\users\papi\appdata\local\pip\cache\wheels\04\7d\d9\68956b3da44dbef65b150faff8a9810209588de332ebe1fa63
Successfully built cairocffi
Installing collected packages: tinycss2, cssselect2, pycparser, cffi, cairocffi, pillow, CairoSVG, Pyphen, weasyprint
Successfully installed CairoSVG-2.4.2 Pyphen-0.9.5 cairocffi-1.1.0 cffi-1.14.0 cssselect2-0.3.0 pillow-7.1.2 pycparser-2.20 tinycss2-1.0.2 weasyprint-51

```
using python 3.7.7 on windows 10 64b with miniconda 3

**Comment by milkywade** [comment]
unsubscribing as I removed weasyprint to use pdfkit instead
