### ISSUE TITLE
No module named 'cairocffi._generated'

### ISSUE THREAD

**Issue by carloseustaquio** [Kozea/cairocffi#201]
Not working on a project using PDM running on WSL2, Ubuntu 20.04. I've inspected the code and it seems that this module actually doesn't exist.

```sh
❯ pdm run start
Traceback (most recent call last):
  (...)
    from . import computed_values, counters, media_queries
  File "/home/my-project/__pypackages__/3.9/lib/weasyprint/css/computed_values.py", line 15, in <module>
    from .. import text
  File "/home/my-project/__pypackages__/3.9/lib/weasyprint/text.py", line 11, in <module>
    import cairocffi as cairo
  File "/home/my-project/__pypackages__/3.9/lib/cairocffi/__init__.py", line 17, in <module>
    from ._generated.ffi import ffi
ModuleNotFoundError: No module named 'cairocffi._generated'
```

![image](https://user-images.githubusercontent.com/43277022/162526438-e4edfa88-c5c7-4e67-8d7e-488ed9804a83.png)

**Comment by liZe** [comment]
Hello!

The `_generated` module is created when you install CairoSVG. If you installed it using `pip`, it should be there.

**Comment by carloseustaquio** [comment]
I'm installing it using [PDM](https://pdm.fming.dev/). It's installing both packages, but for some reason, it's not creating the `_generated` module 🤔

**Comment by liZe** [comment]
What you can do is:
- remove CairoCFFI’s wheel that’s been created in `~/.cache/pdm/wheels`
- `pdm init`
- `pdm add cairocffi -v`

In the logs, you should have something like
```
[…]
Building wheel for https://files.pythonhosted.org/packages/8b/d2/137b346d64f0d6428a90f60b51a06706592a86b74fd21ff66c853537cb9b/cairocffi-1.3.0.tar.gz#sha256=108a3a7cb09e203bdd8501d9baad91d786d204561bd71e9364e8b34897c47b91 (from https://pypi.org/simple/cairocffi/) (requires-python:>=3.7)
Collecting wheel
  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Collecting setuptools>=40.8.0
  Using cached setuptools-62.1.0-py3-none-any.whl (1.1 MB)
Installing collected packages: wheel, setuptools
Successfully installed setuptools-62.1.0 wheel-0.37.1
[…]
creating build
creating build/lib
creating build/lib/cairocffi
copying cairocffi/xcb.py -> build/lib/cairocffi
copying cairocffi/test_xcb.py -> build/lib/cairocffi
copying cairocffi/test_pixbuf.py -> build/lib/cairocffi
copying cairocffi/test_numpy.py -> build/lib/cairocffi
copying cairocffi/test_cairo.py -> build/lib/cairocffi
copying cairocffi/surfaces.py -> build/lib/cairocffi
copying cairocffi/pixbuf.py -> build/lib/cairocffi
copying cairocffi/patterns.py -> build/lib/cairocffi
copying cairocffi/matrix.py -> build/lib/cairocffi
copying cairocffi/fonts.py -> build/lib/cairocffi
copying cairocffi/ffi_build.py -> build/lib/cairocffi
copying cairocffi/context.py -> build/lib/cairocffi
copying cairocffi/constants.py -> build/lib/cairocffi
copying cairocffi/__init__.py -> build/lib/cairocffi
copying cairocffi/VERSION -> build/lib/cairocffi
file cairocffi/_generated/ffi.py (for module cairocffi._generated.ffi) not found
file cairocffi/_generated/ffi_pixbuf.py (for module cairocffi._generated.ffi_pixbuf) not found
generating cffi module 'build/lib/cairocffi/_generated/ffi.py'
creating build/lib/cairocffi/_generated
generating cffi module 'build/lib/cairocffi/_generated/ffi_pixbuf.py'
[…]
```

If you don’t, maybe you have an old version of setuptools and should update it.

**Comment by carloseustaquio** [comment]
Oh... That fixed the issue! Thank you very much!
