### ISSUE TITLE
Document installation for OSX (cannot import name constants)

### ISSUE THREAD

**Issue by nitinbodke** [Kozea/cairocffi#29]
I am trying to install Graphite. I am stuck upon cairo installation. 
I came across "http://stackoverflow.com/questions/11491268/install-pycairo-in-virtualenv".
I have installed cairocffi in my virtual environment.

My environment is:
"OS X: 10.8.5
Python: 2.7.2
Virtual Env:
pip list
cairocffi (0.5.1)
ceres (0.10.0)
cffi (0.8.1)
Django (1.5.5)
django-tagging (0.3.1)
pip (1.5)
pycparser (2.10)
setuptools (2.0.2)
Twisted (11.1.0)
txAMQP (0.6.2)
whisper (0.9.12)
wsgiref (0.1.2)
zope.interface (4.0.5)"

Cairo:
I have installed cairo using macports.
"cairo @1.12.16_2+x11 (active)"

I started graphite with following sequence of commands: 
1. source /opt/graphite/bin/activate
2. sudo /opt/graphite/bin/carbon-cache.py start
3. sudo ./bin/run-graphite-devel-server.py /opt/graphite

http://0.0.0.0:8080/ is displaying Graphite home page.
But http://0.0.0.0:8080/render produces following traceback:

```
Traceback (most recent call last):
  File "/opt/graphite/lib/python2.7/site-packages/django/core/handlers/base.py", line 103, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/opt/graphite/lib/python2.7/site-packages/django/core/urlresolvers.py", line 321, in resolve
    sub_match = pattern.resolve(new_path)
  File "/opt/graphite/lib/python2.7/site-packages/django/core/urlresolvers.py", line 321, in resolve
    sub_match = pattern.resolve(new_path)
  File "/opt/graphite/lib/python2.7/site-packages/django/core/urlresolvers.py", line 223, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/opt/graphite/lib/python2.7/site-packages/django/core/urlresolvers.py", line 230, in callback
    self._callback = get_callable(self._callback_str)
  File "/opt/graphite/lib/python2.7/site-packages/django/utils/functional.py", line 31, in wrapper
    result = func(*args)
  File "/opt/graphite/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/opt/graphite/lib/python2.7/site-packages/django/utils/importlib.py", line 35, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/render/views.py", line 36, in <module>
    from graphite.render.evaluator import evaluateTarget
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 47, in <module>
    from graphite.render.functions import SeriesFunctions
  File "/opt/graphite/webapp/graphite/render/functions.py", line 33, in <module>
    from graphite.render.glyph import format_units
  File "/opt/graphite/webapp/graphite/render/glyph.py", line 15, in <module>
    import cairocffi as cairo
  File "/opt/graphite/lib/python2.7/site-packages/cairocffi/__init__.py", line 16, in <module>
    from . import constants
ImportError: cannot import name constants
```

**Comment by YangLeoZhao-Reflektion** [comment]
Hi Guys, 
I just tried to install Graphite following the https://gist.github.com/relaxdiego/7539911 guide step by step. However, i'm encountering the error 

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Library/Python/2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/render/views.py", line 37, in <module>
    from graphite.render.evaluator import evaluateTarget, extractPathExpressions
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 69, in <module>
    from graphite.render.functions import SeriesFunctions
  File "/opt/graphite/webapp/graphite/render/functions.py", line 34, in <module>
    from graphite.render.glyph import format_units
  File "/opt/graphite/webapp/graphite/render/glyph.py", line 20, in <module>
    import cairocffi as cairo
<b>ImportError: No module named cairocffi</b>

I have installed everything in a virenv and check with pip list that everything is indeed installed. 

In the installation form, they mentioned "If you get a broken image, it most likely means that something is wrong py2cairo and cairo."

Leos-Macbook:graphite yang.zhao$ brew install cairo
Warning: cairo-1.14.0 already installed
Leos-Macbook:graphite yang.zhao$ brew install py2cairo
Warning: py2cairo-1.10.0 already installed

Both of them seem to be installed. 

I have also verified cairocffi is installed as well.

Leos-Macbook:graphite yang.zhao$ python
Python 2.7.6 (default, Nov 18 2013, 15:12:51) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
'>>> import cairocffi'
'>>> '

Please advise

**Comment by chander** [comment]
If it's helpful to anyone, I had this error (sadly, I didn't capture the entire traceback):

  File "/opt/graphite/lib/python2.6/site-packages/cairocffi/__init__.py", line 16, in <module>
    from . import constants
ImportError: cannot import name constants

The issue turned out to be Security Enhanced Linux preventing the read (by the web server) of the constants module.  I'm not sure why some of the reads worked and others didn't, but in my case running the appropriate chcon command fixed the issue.

**Comment by dkelsey** [comment]
I'm experiencing the same ImportError: cannot import name constants issue.
My setup:

```
OSX 10.10.2
Python: 2.7.9
pip list
cairocffi (0.6)
cffi (0.8.6)
constants (0.6.0)
Django (1.7.4)
django-tagging (0.3.4)
elasticsearch (1.1.1)
elasticsearch-curator (1.1.2)
mysql-connector-python (1.2.2)
mysql-utilities (1.4.4)
pip (1.5.6)
pycparser (2.10)
python-memcached (1.53)
setuptools (7.0)
Twisted (15.0.0)
txAMQP (0.6.2)
urllib3 (1.8.3)
vboxapi (1.0)
whisper (0.9.13)
wsgiref (0.1.2)
zope.interface (4.1.2)

Cairo:
I built it from source: 
cairo-1.14.0
```

I initially followed the instructions from : (http://graphite.wikidot.com/installation) and built modules from source.
I setup everything including ```mod_wsgi``` in the latest Apache.
After starting everything that failed with the ```"ImportError"``` -- in fact it looks like when I first request the dashboard the error is 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/dashboard/views.py", line 13, in <module>
    from graphite.render.views import renderView
  File "/opt/graphite/webapp/graphite/render/views.py", line 37, in <module>
    from graphite.render.evaluator import evaluateTarget, extractPathExpressions
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 69, in <module>
    from graphite.render.functions import SeriesFunctions
  File "/opt/graphite/webapp/graphite/render/functions.py", line 34, in <module>
    from graphite.render.glyph import format_units
  File "/opt/graphite/webapp/graphite/render/glyph.py", line 20, in <module>
    import cairocffi as cairo
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cairocffi/__init__.py", line 41, in <module>
    cairo = dlopen(ffi, *CAIRO_NAMES)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cairocffi/__init__.py", line 34, in dlopen
    return ffi.dlopen(names[0])  # pragma: no cover
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 118, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 411, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cffi/api.py", line 400, in _load_backend_lib
    return backend.load_library(name, flags)
OSError: cannot load library libcairo.so.2: dlopen(libcairo.so.2, 2): image not found
```
Subsequent requests are: 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/handlers/base.py", line 98, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 345, in resolve
    sub_match = pattern.resolve(new_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 224, in resolve
    return ResolverMatch(self.callback, args, kwargs, self.name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 231, in callback
    self._callback = get_callable(self._callback_str)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/utils/lru_cache.py", line 101, in wrapper
    result = user_function(*args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/django/core/urlresolvers.py", line 97, in get_callable
    mod = import_module(mod_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/opt/graphite/webapp/graphite/dashboard/views.py", line 13, in <module>
    from graphite.render.views import renderView
  File "/opt/graphite/webapp/graphite/render/views.py", line 37, in <module>
    from graphite.render.evaluator import evaluateTarget, extractPathExpressions
  File "/opt/graphite/webapp/graphite/render/evaluator.py", line 69, in <module>
    from graphite.render.functions import SeriesFunctions
  File "/opt/graphite/webapp/graphite/render/functions.py", line 34, in <module>
    from graphite.render.glyph import format_units
  File "/opt/graphite/webapp/graphite/render/glyph.py", line 20, in <module>
    import cairocffi as cairo
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/cairocffi/__init__.py", line 16, in <module>
    from . import constants
ImportError: cannot import name constants
```

Soldiering on, I found this post and others about the issue.
I then followed the instructions from:  (https://gist.github.com/relaxdiego/7539911) -- installing everything using ```pip```.

Starting carbon and graphite from the command line worked:  when I navigate to (http://localhost:8080/dashboard/)  there are no errors; everything looks to be fully functioning.

Very puzzling. 

I then discovered something:  
I had:
```
/usr/bin/python -> 2.7.6
/usr/local/bin/python -> 2.7.9
```

pip's sh-bang was ```/usr/bin/python```

I changed it to the latter. then found that starting graphite from the command line failed with missing modules.

I re-added the modules and got graphite back working again.
I shut down ```apache```, recompiled ```mod_wsgi```, re-installed, and started apache again. 
 
...and.  The problem persists: same same ```OSError: cannot load library libcairo.so.2: dlopen(libcairo.so.2, 2): image not found``` and ```ImportError: cannot import name constants```
errors.

So the ```python``` launched carbon/graphite works yet the ```Apache``` with ```mod_wsgi``` versions does not.

```python -c 'import cairocffi'``` succeeds without error.

and going even further:

I noticed that the architecture for ```libcairo``` was ```x86_64``` where as apache and ```mod_wsgi``` is ```i386```.
So I recompiled ```libcairo``` with ```CFLAGS="-arch i386 -arch x86_64" LDFLAGS="-arch i386 -arch x86_64"```.
I had to do the same for dependancies: ```libpng16``` and ```libpixman-1```.
There were warnings about ```pthread``` which i've ignored.

re-started apache and still I get both the ```dlopen``` and ```import``` errors.

I'm still wondering what it could be.

**Comment by dkelsey** [comment]
OK.  I've had some success.
It was the ```i386``` vs ```x86_64``` arch as I suspected.
I missed rebuilding ```py2cairo```: ```py2cairo-1.10.0```

```
cat doit
./waf clean
export PYTHONPATH=/Library/Frameworks/Python.framework/Versions/2.7/
export LD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/2.7/:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/Library/Frameworks/Python.framework/Versions/2.7/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/opt/dmk/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/opt/dmk/lib/cairo:$LD_LIBRARY_PATH
#export LINKFLAGS='-search_dylibs_first  -L /Library/Frameworks/Python.framework/Versions/2.7/lib/'
export LINKFLAGS='-L/opt/dmk/lib -L/opt/dmk/lib/cairo -L/Library/Frameworks/Python.framework/Versions/2.7/lib/'
export ARCHFLAGS='-arch x86_64 -arch i386'
#export CC=/usr/bin/gcc-4.2 # let it find gcc /usr/bin/gcc in my case
export PKG_CONFIG_PATH=/opt/dmk/lib/pkgconfig/

./waf configure --prefix=$PYTHONPATH
./waf build
./waf install
```
I run:
```
. doit
``` 
to get the whole thing rolling.

Note: I added ```-arch i386``` to the ```ARCHFLAGS```. 
Rebuilt and installed--as it says in ```doit```.
Restarted ```Apache``` and success!!!

```apache``` is 32bit, as i've built it.  It won't find/load ```x86_64``` libraries.

I think my problem was 
a) strange configuration of python (```/usr/bin/python``` vs ```/usr/local/bin/python```)
b) incompatibility of architectures of misc dependancies.

**Comment by cdosborn** [comment]
I don't know why, but `apt-get install python-cairo-dev` fixed my issue (same as OP)

**Comment by scuerda** [comment]
I was experiencing many of the same problems in relation to installing WeasyPrint in a virtualenv on a clean vagrant box. 

@cdosborn suggestion worked like a charm for me as well.

**Comment by wangalice** [comment]
Thanks for the answer all above, I met this problem yesterday. By reading your answers, it solved by "brew install cairo"finnally lol

**Comment by liZe** [comment]
We probably need a better documentation for OSX!

**Comment by fvdoorn1970** [comment]
Not sure if you already have an answer on this one, but I had the same issue today.
Situation:
I upgraded to OSX Sierra. Since El Capitan Apple decided to do some SIP stuff (see: http://apple.stackexchange.com/questions/212945/unable-to-set-dyld-fallback-library-path-in-shell-on-osx-10-11-1).

As a result, when using cairocffi using plain Python, it will work. At least on my configuration. However, when using the shell of Django or start the run server, your env settings like DYLD_FALLBACK_LIBRARY_PATH are simply gone. A new shell starts and the env setting is gone.

In my situation (running Django and using Weasyprint) I solved it by adding this line in my manage.py:
`os.environ.setdefault("DYLD_FALLBACK_LIBRARY_PATH", "/opt/local/lib")`

I'm using port (not brew).

Also note: after upgrading a working system to El Capitan or higher, consider recreating your virtualenv.

**Comment by obarthel** [comment]
I struggled with the `DYLD_FALLBACK_LIBRARY_PATH` environment variable, too, on OSX Sierra, with MacPorts installed. Not even the test code I wrote would work when launched from shell, in spite of `DYLD_FALLBACK_LIBRARY_PATH` being set correctly. So, while you may be able to work around the problem within Django, there had to be a "better" way.

My solution was to hack the _WeasyPrint_ and _cairocffi_ Python packages after they were installed, so that they would work with MacPorts. The problem resides with the `dlopen()` calls in `weasyprint/text.py` and `cairocffi/__init__.py`, respectively. None of them will look into `/opt/local/lib`, and the library names used were not always prefixed by `lib`.

Here is how I modified `/Library/Python/2.7/site-packages/weasyprint/text.py`:

```python
def dlopen(ffi, *names):
    """Try various names for the same library, for different platforms."""
    for name in names:
        for lib_name in [name, '/opt/local/lib/'+name]:
            try:
                return ffi.dlopen(lib_name)
            except OSError:
                pass
    # Re-raise the exception.
    return ffi.dlopen(names[0])  # pragma: no cover
```

These are the changes for `/Library/Python/2.7/site-packages/cairocffi/__init__.py`:

```python
def dlopen(ffi, *names):
    """Try various names for the same library, for different platforms."""
    for name in names:
        for lib_name in [name, 'lib' + name, '/opt/local/lib/lib' + name]:
            try:
                path = ctypes.util.find_library(lib_name)
                if path:
                    lib = ffi.dlopen(path)
                    if lib:
                        return lib
            except OSError:
                pass
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
```

Not an elegant solution, I grant you, but it gets the job done.
