### ISSUE TITLE
ffi.include() expects an argument that is also of type cffi.FFI, not 'CompiledFFI'

### ISSUE THREAD

**Issue by ptosco** [Kozea/cairocffi#87]
Hello,
I am using cffi-1.7.0 and  cairocffi-0.7.2 under Python 3. When I try the example reported here:
[https://pythonhosted.org/cairocffi/cffi_api.html#example-using-pango-through-cffi-with-cairocffi](url)
it fails on this command
`ffi.include(cairocffi.ffi)`
with the following error message:
TypeError: ffi.include() expects an argument that is also of type cffi.FFI, not 'CompiledFFI'

I get the same error message under both Linux (Python 3.4) and Windows (Python 3.5).
Is there any obvious solution I am missing?
Thanks a lot for your help!

**Comment by SimonSapin** [comment]
My first guess is that this example needs to be updated to use "out of line" style: https://pythonhosted.org/cairocffi/cffi_api.html#example-using-pango-through-cffi-with-cairocffi

**Comment by ptosco** [comment]
Thanks Simon, I managed to get things to work without problems. The ffi.include() is not actually needed as long as the required prototypes are defined in the cdef.

**Comment by rakeshvar** [comment]
I (and @ChillarAnand) have the same problem. I just copied the text from the link and get the same error.
 
```sh
$ python3 mycffi.py 
Traceback (most recent call last):
  File "mycffi.py", line 7, in <module>
    ffi.include(cairocffi.ffi)
  File "/usr/local/lib/python3.4/dist-packages/cffi/api.py", line 494, in include
    type(ffi_to_include).__name__,))
TypeError: ffi.include() expects an argument that is also of type cffi.FFI, not 'CompiledFFI'
```
I commented out `#ffi.include(cairocffi.ffi)` and get the following error:
 
```sh
$ python3 mycffi.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cffi/cparser.py", line 260, in _parse
    ast = _get_parser().parse(csource)
  File "/usr/local/lib/python3.4/dist-packages/pycparser/c_parser.py", line 146, in parse
    debug=debuglevel)
  File "/usr/local/lib/python3.4/dist-packages/pycparser/ply/yacc.py", line 265, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "/usr/local/lib/python3.4/dist-packages/pycparser/ply/yacc.py", line 1047, in parseopt_notrack
    tok = self.errorfunc(errtoken)
  File "/usr/local/lib/python3.4/dist-packages/pycparser/c_parser.py", line 1680, in p_error
    column=self.clex.find_tok_column(p)))
  File "/usr/local/lib/python3.4/dist-packages/pycparser/plyparser.py", line 55, in _parse_error
    raise ParseError("%s: %s" % (coord, msg))
pycparser.plyparser.ParseError: :15:54: before: *

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mycffi.py", line 28, in <module>
    ''')
  File "/usr/local/lib/python3.4/dist-packages/cffi/api.py", line 105, in cdef
    self._cdef(csource, override=override, packed=packed)
  File "/usr/local/lib/python3.4/dist-packages/cffi/api.py", line 119, in _cdef
    self._parser.parse(csource, override=override, **options)
  File "/usr/local/lib/python3.4/dist-packages/cffi/cparser.py", line 299, in parse
    self._internal_parse(csource)
  File "/usr/local/lib/python3.4/dist-packages/cffi/cparser.py", line 304, in _internal_parse
    ast, macros, csource = self._parse(csource)
  File "/usr/local/lib/python3.4/dist-packages/cffi/cparser.py", line 262, in _parse
    self.convert_pycparser_error(e, csource)
  File "/usr/local/lib/python3.4/dist-packages/cffi/cparser.py", line 291, in convert_pycparser_error
    raise api.CDefError(msg)
cffi.api.CDefError: cannot parse "PangoLayout * pango_cairo_create_layout (cairo_t *cr);"
:15:54: before: *
```

To circumvent this, if I add the line `typedef int... cairo_t;` as 
```py
ffi.cdef('''
    typedef int... cairo_t;
    /* GLib */
```
then it imports ok, but gives a runtime error. 
```sh
$ python3 mycffi.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cffi/api.py", line 406, in _get_cached_btype
    BType = self._cached_btypes[type]
KeyError: <PangoLayout *(*)(cairo_t *)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 59, in get_cached_btype
    BType = ffi._cached_btypes[self]
KeyError: <PangoLayout *(*)(cairo_t *)>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 59, in get_cached_btype
    BType = ffi._cached_btypes[self]
KeyError: <cairo_t *>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 59, in get_cached_btype
    BType = ffi._cached_btypes[self]
KeyError: <cairo_t>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mycffi.py", line 57, in <module>
    write_example_pdf(target='pango_example.pdf')
  File "mycffi.py", line 47, in write_example_pdf
    pangocairo.pango_cairo_create_layout(context._pointer))
  File "/usr/local/lib/python3.4/dist-packages/cffi/api.py", line 837, in __getattr__
    make_accessor(name)
  File "/usr/local/lib/python3.4/dist-packages/cffi/api.py", line 833, in make_accessor
    accessors[name](name)
  File "/usr/local/lib/python3.4/dist-packages/cffi/api.py", line 774, in accessor_function
    BType = ffi._get_cached_btype(tp)
  File "/usr/local/lib/python3.4/dist-packages/cffi/api.py", line 409, in _get_cached_btype
    BType = type.get_cached_btype(self, finishlist)
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 61, in get_cached_btype
    BType = self.build_backend_type(ffi, finishlist)
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 241, in build_backend_type
    args.append(tp.get_cached_btype(ffi, finishlist))
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 61, in get_cached_btype
    BType = self.build_backend_type(ffi, finishlist)
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 268, in build_backend_type
    BItem = self.totype.get_cached_btype(ffi, finishlist, can_delay=True)
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 61, in get_cached_btype
    BType = self.build_backend_type(ffi, finishlist)
  File "/usr/local/lib/python3.4/dist-packages/cffi/model.py", line 184, in build_backend_type
    "compilation" % self.name)
NotImplementedError: integer type 'cairo_t' can only be used after compilation
```

@ptosco what do you mean when you say "The ffi.include() is not actually needed as long as the required prototypes are defined in the cdef."?

Thanks.

**Comment by ptosco** [comment]
@rakeshvar Hi Rakeshvar, please have a look here:
https://github.com/ptosco/rdkit/blob/pangocffi/rdkit/Chem/Draw/cairoCanvas.py#L40
for an example of the way I managed to get things to work for me.

**Comment by rakeshvar** [comment]
@ptosco Thank you. 
```py
ffi.cdef('''
    typedef void cairo_t;
    ...
```
seems to work.
