### ISSUE TITLE
Issue with the installation on linux (in a virtualenv)

### ISSUE THREAD

**Issue by pierre-24** [Kozea/cairocffi#91]
Hello.

In order to install cairosvg, I need to install cairocffi. But when I do so, I get an error:

```
(zdsenv)pbeaujea@chim13-cptrx04 ~/Devels/zds-site $ pip install cairocffi
Collecting cairocffi
  Using cached cairocffi-0.7.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-cOsSB7/cairocffi/setup.py", line 65, in <module>
        **cffi_args
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 181, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 48, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/setuptools_ext.py", line 24, in execfile
        exec(code, glob, glob)
      File "cairocffi/ffi_build.py", line 30, in <module>
        ffi.cdef(constants._CAIRO_HEADERS)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/api.py", line 105, in cdef
        self._cdef(csource, override=override, packed=packed)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/api.py", line 119, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/cparser.py", line 299, in parse
        self._internal_parse(csource)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/cparser.py", line 304, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/cparser.py", line 260, in _parse
        ast = _get_parser().parse(csource)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/cffi/cparser.py", line 40, in _get_parser
        _parser_cache = pycparser.CParser()
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/pycparser/c_parser.py", line 87, in __init__
        outputdir=taboutputdir)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/pycparser/c_lexer.py", line 66, in build
        self.lexer = lex.lex(object=self, **kwargs)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/pycparser/ply/lex.py", line 911, in lex
        lexobj.readtab(lextab, ldict)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/local/lib/python2.7/site-packages/pycparser/ply/lex.py", line 233, in readtab
        titem.append((re.compile(pat, lextab._lexreflags | re.VERBOSE), _names_to_funcs(func_name, fdict)))
      File "/home/pbeaujea/Devels/zds-site/zdsenv/lib/python2.7/re.py", line 190, in compile
        return _compile(pattern, flags)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/lib/python2.7/re.py", line 242, in _compile
        p = sre_compile.compile(pattern, flags)
      File "/home/pbeaujea/Devels/zds-site/zdsenv/lib/python2.7/sre_compile.py", line 509, in compile
        "sorry, but this version only supports 100 named groups"
    AssertionError: sorry, but this version only supports 100 named groups
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-cOsSB7/cairocffi/
```

The end of the backtrace seems to be related to pycparser, so I'm not exactly sure that this is related to cairocffi, but I don't have any other package in mind that require pycparser, so I cannot test.

I'm running Linux Mint 17.3, and I did try to install cffi, python-dev, and python-pycparser trough apt-get (and trough pip for cffi and pycparser), but nothing change. This is, in each case, the latest version of the packages.

Thanks in advance for your help :)

**Comment by aslagle** [comment]
I'm getting this too. It looks like it's related to https://github.com/eliben/pycparser/issues/148, but that was fixed so I don't know why it still happens in cairocffi. 

The `pip install git+https://github.com/eliben/pycparser@release_v2.14` workaround fixed it for me.

**Comment by pierre-24** [comment]
Works for me as well, thanks :)

**Comment by liZe** [comment]
Duplicates #91.
