### ISSUE TITLE
pycparser requirement breaking installation

### ISSUE THREAD

**Issue by maxcountryman** [Kozea/cairocffi#92]
Most likely related to https://github.com/eliben/pycparser/issues/147. Unfortunately downgrading pycparser doesn't help because `cffi` requires a broken `pycparser` release.

```
Collecting cairocffi (from cairosvg==1.0.22->-r requirements.txt (line 3))
  Downloading cairocffi-0.7.2.tar.gz (75kB)
    Complete output from command python setup.py egg_info:

    Installed /tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg
    Searching for pycparser
    Reading https://pypi.python.org/simple/pycparser/
    Best match: pycparser 2.15
    Downloading https://pypi.python.org/packages/37/05/65d342ba500c6f9dbb1978e9dd01a1097530e0291003638bbef329ad4522/pycparser-2.15.tar.gz#md5=8629238be71db4d3f79b4fb1cd1397dc
    Processing pycparser-2.15.tar.gz
    Writing /tmp/easy_install-3wCFkV/pycparser-2.15/setup.cfg
    Running pycparser-2.15/setup.py -q bdist_egg --dist-dir /tmp/easy_install-3wCFkV/pycparser-2.15/egg-dist-tmp-7nwd2_
    warning: no previously-included files matching 'yacctab.*' found under directory 'tests'
    warning: no previously-included files matching 'lextab.*' found under directory 'tests'
    warning: no previously-included files matching 'yacctab.*' found under directory 'examples'
    warning: no previously-included files matching 'lextab.*' found under directory 'examples'
    zip_safe flag not set; analyzing archive contents...
    pycparser.ply.lex: module references __file__
    pycparser.ply.lex: module MAY be using inspect.getsourcefile
    pycparser.ply.ygen: module references __file__
    pycparser.ply.yacc: module references __file__
    pycparser.ply.yacc: module MAY be using inspect.getsourcefile
    pycparser.ply.yacc: module MAY be using inspect.stack
    creating /tmp/pip-build-rfnnAN/cairocffi/.eggs/pycparser-2.15-py2.7.egg
    Extracting pycparser-2.15-py2.7.egg to /tmp/pip-build-rfnnAN/cairocffi/.eggs

    Installed /tmp/pip-build-rfnnAN/cairocffi/.eggs/pycparser-2.15-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-rfnnAN/cairocffi/setup.py", line 65, in <module>
        **cffi_args
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 181, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 48, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/setuptools_ext.py", line 24, in execfile
        exec(code, glob, glob)
      File "cairocffi/ffi_build.py", line 30, in <module>
        ffi.cdef(constants._CAIRO_HEADERS)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/api.py", line 105, in cdef
        self._cdef(csource, override=override, packed=packed)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/api.py", line 119, in _cdef
        self._parser.parse(csource, override=override, **options)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 299, in parse
        self._internal_parse(csource)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 304, in _internal_parse
        ast, macros, csource = self._parse(csource)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 260, in _parse
        ast = _get_parser().parse(csource)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/cffi-1.8.3-py2.7-linux-x86_64.egg/cffi/cparser.py", line 40, in _get_parser
        _parser_cache = pycparser.CParser()
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/pycparser-2.15-py2.7.egg/pycparser/c_parser.py", line 87, in __init__
        outputdir=taboutputdir)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/pycparser-2.15-py2.7.egg/pycparser/c_lexer.py", line 66, in build
        self.lexer = lex.lex(object=self, **kwargs)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/pycparser-2.15-py2.7.egg/pycparser/ply/lex.py", line 911, in lex
        lexobj.readtab(lextab, ldict)
      File "/tmp/pip-build-rfnnAN/cairocffi/.eggs/pycparser-2.15-py2.7.egg/pycparser/ply/lex.py", line 233, in readtab
        titem.append((re.compile(pat, lextab._lexreflags | re.VERBOSE), _names_to_funcs(func_name, fdict)))
      File "/usr/lib/python2.7/re.py", line 194, in compile
        return _compile(pattern, flags)
      File "/usr/lib/python2.7/re.py", line 249, in _compile
        p = sre_compile.compile(pattern, flags)
      File "/usr/lib/python2.7/sre_compile.py", line 583, in compile
        "sorry, but this version only supports 100 named groups"
    AssertionError: sorry, but this version only supports 100 named groups
```

Pinning `cffi` to 1.1.0 fixed the issue for now.

**Comment by senyai** [comment]
I'm sure the issue itself was fixed in `pycparser` and `cffi` and current not relevant to `cairocffi`.

**Comment by liZe** [comment]
It duplicates #91 (there's a workaround in the comments).
